### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [jfhbrook/node-sendgrid-web#7]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by jfhbrook** [comment]
I don't use this module anymore, haven't in years.

Do you want to take it over?

**Comment by thinkingserious** [comment]
Thanks for the update!

We do not need to take it over, but we would appreciate it if you could point people to our latest supported library: https://github.com/sendgrid/sendgrid-nodejs
